In [1]:
import pandas as pd

In [6]:
integrated = pd.read_csv('Expert_Unieuro_Euronics_ALL_MATCHES.csv')

In [5]:
integrated

,Expert,Unieuro,Euronics,Expert Price,Unieuro Price,Euronics Price,Expert Category,Unieuro Category,Euronics Category,Expert Brand,Unieuro Brand,Euronics Brand,Expert Color,Unieuro Color,Euronics Color,Match Type
0,iphone 16 128gb,iphone 16 128gb,iphone 16 128gb,888.90,779.0,979.0,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,nero,nero,nero,3-way match
1,galaxy s24 8+256gb onyx,NaN,galaxy s24 256gb-onyx,707.90,NaN,599.0,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,black,NaN,black,2-way match
2,galaxy s25 ultra 12+512gb,NaN,NaN,1614.90,NaN,NaN,smartphone & cellulari,NaN,NaN,samsung,NaN,NaN,titanium silverblue,NaN,NaN,1-way only
3,redmi note 14 5g 8g ram 256g rom,NaN,redmi note 14 5g 8+256g,255.90,NaN,299.9,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,midnight black,NaN,midnight black,2-way match
4,"edge 50 neo, 8/256gb, fotocamera sony lytia™ 7...",NaN,NaN,341.90,NaN,NaN,smartphone & cellulari,NaN,NaN,motorola,NaN,NaN,unspecified,NaN,NaN,1-way only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10541,6206301401,NaN,NaN,11.99,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10542,6016101401,NaN,NaN,4.50,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10543,6430101401,NaN,NaN,2.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10544,pila bottone x eletronica cr2450 litio,NaN,NaN,3.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10545,4276101401,NaN,NaN,1.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only

## Quality Assessment

### Accuracy

In [7]:
quality_Expert = integrated[
    integrated['Expert Category'] == 'smartphone & cellulari'
].dropna(subset=['Unieuro', 'Euronics'], thresh=1).sample(50)

quality_Expert.reset_index(drop=True, inplace=True)
quality_Expert

,Expert,Unieuro,Euronics,Expert Price,Unieuro Price,Euronics Price,Expert Category,Unieuro Category,Euronics Category,Expert Brand,Unieuro Brand,Euronics Brand,Expert Color,Unieuro Color,Euronics Color,Match Type
0,iphone 16 plus 128gb,iphone 16 plus 128gb,iphone 16 plus 128gb,1011.90,999.0,1069.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,nero,nero,nero,3-way match
1,redmi 14c 4gb ram 128gb rom,NaN,smartphone redmi 14c 4+128gb,99.90,NaN,99.90,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,sage green,NaN,midnight black,2-way match
2,redmi note 14 pro 5g 8gb ram 256gb rom,NaN,smartphone redmi note 12 pro+ 5g 8+256gb,349.90,NaN,319.00,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,lavender purple,NaN,midnight black,2-way match
3,galaxy s25+ 12+256gb icy,NaN,smartphone galaxy s25 256gb-icy,1147.00,NaN,885.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,blue,NaN,blue,2-way match
4,onetouch 4043 grey,NaN,cellulare onetouch 4043-grey,69.90,NaN,65.90,smartphone & cellulari,NaN,smartphone e cellulari,tcl,NaN,tcl,gray,NaN,gray,2-way match
5,galaxy s24 ultra 12+512gb,NaN,galaxy s24 ultra 512gb,1459.90,NaN,1619.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium black,NaN,titanium gray,2-way match
6,105 2024,NaN,cellulare 105 2024,29.90,NaN,30.49,smartphone & cellulari,NaN,smartphone e cellulari,nokia,NaN,nokia,black,NaN,black,2-way match
7,iphone 15 pro max 256gb,NaN,iphone 15 pro 256gb,1299.00,NaN,1369.00,smartphone & cellulari,NaN,smartphone e cellulari,apple,NaN,apple,titanio blu,NaN,titanio blu,2-way match
8,iphone 16e 128gb,iphone 16e 128gb,iphone 16e 128gb,711.90,699.0,729.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,nero,nero,nero,3-way match
9,galaxy s24 onyx 8+128gb,NaN,galaxy s24 256gb-onyx,1092.90,NaN,599.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,black,NaN,black,2-way match
10,redmi note 14 5g 8g ram 256g rom,NaN,redmi note 14 5g 8+256g,255.90,NaN,299.90,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,midnight black,NaN,midnight black,2-way match
11,iphone 16e 256gb,iphone 16e 256gb,iphone 16e 256gb,832.90,829.0,859.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,nero,nero,nero,3-way match
12,galaxy s24 8+256gb,NaN,galaxy s24 256gb,729.90,NaN,599.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,amber yellow,NaN,marble gray,2-way match
13,galaxy a36 5g 8+256gb,NaN,smartphone galaxy a36 5g 256gb,421.90,NaN,459.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,awesome lime,NaN,awesome lime,2-way match
14,galaxy s25 12+256gb,NaN,smartphone galaxy s25+ 256gb,943.90,NaN,1234.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,navy,NaN,mint,2-way match
15,galaxy s25 ultra 12+1tb,NaN,smartphone galaxy s25 ultra 1tb,1712.90,NaN,1466.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium whitesilver,NaN,titanium black,2-way match
16,galaxy s25 12+512gb,NaN,smartphone galaxy s25+ 512gb,1059.90,NaN,1358.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,navy,NaN,mint,2-way match
17,iphone 16 plus 128gb,iphone 16 plus 128gb,iphone 16 plus 128gb,1027.90,999.0,1069.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,rosa,rosa,nero,3-way match
18,iphone 16 plus 256gb,iphone 16 plus 256gb,iphone 16 plus 256gb,1146.90,1129.0,1189.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,blu oltremare,blu oltremare,verde acqua,3-way match
19,galaxy a55 5g 8+128gb,NaN,galaxy a55 5g 128gb,369.99,NaN,365.00,smartphone & cellulari,NaN,smartphone e cellulari,vodafone,NaN,samsung,black,NaN,awesome iceblue,2-way match
20,50 pro nxtpaper 8/512 5g,NaN,50 nxtpaper,264.90,NaN,199.00,smartphone & cellulari,NaN,smartphone e cellulari,tcl,NaN,tcl,blue,NaN,blue,2-way match
21,galaxy s25 ultra 12+256gb,NaN,smartphone galaxy s25 ultra 256gb,1446.90,NaN,1199.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium whitesilver,NaN,titanium black,2-way match
22,galaxy s25 12+128gb,NaN,smartphone galaxy s25 128gb,895.90,NaN,849.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,navy,NaN,mint,2-way match
23,galaxy s25+ 12+512gb,NaN,smartphone galaxy s25+ 512gb,1249.90,NaN,1358.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,navy,NaN,mint,2-way match
24,galaxy s25+ 12+256gb,NaN,smartphone galaxy s25+ 256gb,1135.90,NaN,1234.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,silver shadow,NaN,mint,2-way match
25,amico smartphone +,amico smartphone pocket,NaN,94.90,49.9,NaN,smartphone & cellulari,smartphone e cellulari,NaN,brondi,brondi,NaN,unspecified,unspecified,NaN,2-way match
26,2660,NaN,2660,79.90,NaN,79.90,smartphone & cellulari,NaN,smartphone e cellulari,nokia,NaN,nokia,black,NaN,black,2-way match
27,galaxy s25 ultra 12+256gb,NaN,smartphone galaxy s25 ultra 256gb,1446.90,NaN,1199.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium gray,NaN,titanium black,2-way match
28,iphone 16 256gb,iphone 16 256gb,iphone 16 256gb,974.90,949.0,1049.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,bianco,bianco,nero,3-way match
29,50 nxtpaper 8/256 5g,NaN,50 nxtpaper,195.90,NaN,199.00,smartphone & cellulari,NaN,smartphone e cellulari,tcl,NaN,tcl,blue,NaN,blue,2-way match
30,iphone 16 plus 256gb,iphone 16 256gb,iphone 16 256gb,1146.90,979.0,1049.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,rosa,rosa,nero,3-way match
31,redmi 14c 8gb ram 256gb rom,NaN,smartphone redmi 14c 8+256gb,195.00,NaN,129.00,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,starry blue,NaN,midnight black,2-way match
32,"reno12 f 4g ai smartphone, camera 50+8+2mp, se...","reno12 f 4g ai smartphone, tripla fotocamera 5...",NaN,212.90,199.0,NaN,smartphone & cellulari,smartphone e cellulari,NaN,oppo,oppo,NaN,amber orange,amber orange,NaN,2-way match
33,galaxy s25 ultra 12+256gb,NaN,smartphone galaxy s25 ultra 256gb,1446.90,NaN,1199.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium black,NaN,titanium black,2-way match
34,galaxy xcover7 5g 6+128gb,NaN,galaxy xcover7 5g,359.90,NaN,289.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,black,NaN,black,2-way match
35,redmi a3 4gb ram 128gb rom,NaN,smartphone redmi a3 4+128gb,89.99,NaN,91.90,smartphone & cellulari,NaN,smartphone e cellulari,tim,NaN,xiaomi,midnight black,NaN,midnight black,2-way match
36,iphone 13 128gb,iphone 13 128gb,iphone 13 128gb,581.90,549.0,629.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,mezzanotte,mezzanotte,mezzanotte,3-way match
37,galaxy a56 5g 8+256gb,NaN,smartphone galaxy a56 5g 256gb,503.90,NaN,439.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,awesome lightgray,NaN,awesome pink,2-way match
38,50 nxtpaper 8/256 5g grey,NaN,50 nxtpaper-grey,195.90,NaN,199.00,smartphone & cellulari,NaN,smartphone e cellulari,tcl,NaN,tcl,gray,NaN,gray,2-way match
39,iphone 16 pro 512gb,iphone 16 pro max 512gb,iphone 16 pro max 512gb,1584.00,1629.0,1739.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,titanio nero,titanio nero,titanio sabbia,3-way match
40,redmi note 14 5g 8g ram 256g rom,NaN,redmi note 14 5g 8+256g,255.90,NaN,299.90,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,lavender purple,NaN,midnight black,2-way match
41,galaxy s25+ 12+512gb,NaN,smartphone galaxy s25+ 512gb,1250.90,NaN,1358.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,mint,NaN,mint,2-way match
42,iphone 16 128gb,iphone 16 128gb,iphone 16 128gb,873.90,779.0,979.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,rosa,rosa,nero,3-way match
43,galaxy s25 ultra 12+1tb,NaN,smartphone galaxy s25 ultra 1tb,1673.90,NaN,1466.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,titanium black,NaN,titanium black,2-way match
44,galaxy a36 5g 6+128gb,NaN,smartphone galaxy a36 5g 128gb,366.90,NaN,315.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,awesome lavender,NaN,awesome lime,2-way match
45,galaxy s25 12+256gb icy,NaN,smartphone galaxy s25 256gb-icy,943.90,NaN,885.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,blue,NaN,blue,2-way match
46,iphone 16 plus 256gb,iphone 16 plus 256gb,iphone 16 plus 256gb,1140.90,1129.0,1189.00,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,verde acqua,verde acqua,verde acqua,3-way match
47,galaxy a16 5g 4+128gb,NaN,smartphone galaxy a16 5g,179.90,NaN,175.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,blue black,NaN,light green,2-way match
48,galaxy s25+ 12+512gb,NaN,smartphone galaxy s25+ 512gb,1262.90,NaN,1358.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,silver shadow,NaN,mint,2-way match
49,galaxy s24 8+128gb,NaN,galaxy s24 256gb,879.00,NaN,599.00,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,marble gray,NaN,marble gray,2-way match

In [8]:
# Iterate over all rows in the quality_Expert dataframe
for i in range(len(quality_Expert)):
    # Print product matches in a more readable format
    print(f"Expert: {quality_Expert.iloc[i]['Expert']}")
    print(f"Unieuro: {quality_Expert.iloc[i]['Unieuro']}")
    print(f"Euronics: {quality_Expert.iloc[i]['Euronics']}")
    print('-' * 30)
    
#correct_matches = 45 over 50 = 90%

Expert: iphone 16 plus 128gb
Unieuro: iphone 16 plus 128gb
Euronics: iphone 16 plus 128gb
------------------------------
Expert: redmi 14c  4gb ram 128gb rom
Unieuro: nan
Euronics: smartphone redmi 14c 4+128gb
------------------------------
Expert: redmi note 14 pro 5g  8gb ram 256gb rom
Unieuro: nan
Euronics: smartphone redmi note 12 pro+ 5g 8+256gb
------------------------------
Expert: galaxy s25+ 12+256gb icy
Unieuro: nan
Euronics: smartphone galaxy s25 256gb-icy
------------------------------
Expert: onetouch 4043 grey
Unieuro: nan
Euronics: cellulare onetouch 4043-grey
------------------------------
Expert: galaxy s24 ultra 12+512gb
Unieuro: nan
Euronics: galaxy s24 ultra 512gb
------------------------------
Expert: 105 2024
Unieuro: nan
Euronics: cellulare 105 2024
------------------------------
Expert: iphone 15 pro max 256gb
Unieuro: nan
Euronics: iphone 15 pro 256gb
------------------------------
Expert: iphone 16e 128gb
Unieuro: iphone 16e 128gb
Euronics: iphone 16e 128gb
------------------------------
Expert: galaxy s24 onyx  8+128gb
Unieuro: nan
Euronics: galaxy s24 256gb-onyx
------------------------------
Expert: redmi note 14 5g  8g ram 256g rom
Unieuro: nan
Euronics: redmi note 14 5g 8+256g
------------------------------
Expert: iphone 16e 256gb
Unieuro: iphone 16e 256gb
Euronics: iphone 16e 256gb
------------------------------
Expert: galaxy s24 8+256gb
Unieuro: nan
Euronics: galaxy s24 256gb
------------------------------
Expert: galaxy a36 5g 8+256gb
Unieuro: nan
Euronics: smartphone galaxy a36 5g 256gb
------------------------------
Expert: galaxy s25 12+256gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 256gb
------------------------------
Expert: galaxy s25 ultra 12+1tb
Unieuro: nan
Euronics: smartphone galaxy s25 ultra 1tb
------------------------------
Expert: galaxy s25 12+512gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 512gb
------------------------------
Expert: iphone 16 plus 128gb
Unieuro: iphone 16 plus 128gb
Euronics: iphone 16 plus 128gb
------------------------------
Expert: iphone 16 plus 256gb
Unieuro: iphone 16 plus 256gb
Euronics: iphone 16 plus 256gb
------------------------------
Expert: galaxy a55 5g 8+128gb
Unieuro: nan
Euronics: galaxy a55 5g 128gb
------------------------------
Expert: 50 pro nxtpaper 8/512 5g
Unieuro: nan
Euronics: 50 nxtpaper
------------------------------
Expert: galaxy s25 ultra 12+256gb
Unieuro: nan
Euronics: smartphone galaxy s25 ultra 256gb
------------------------------
Expert: galaxy s25 12+128gb
Unieuro: nan
Euronics: smartphone galaxy s25 128gb
------------------------------
Expert: galaxy s25+ 12+512gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 512gb
------------------------------
Expert: galaxy s25+ 12+256gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 256gb
------------------------------
Expert: amico smartphone +
Unieuro: amico smartphone pocket
Euronics: nan
------------------------------
Expert: 2660
Unieuro: nan
Euronics: 2660
------------------------------
Expert: galaxy s25 ultra 12+256gb
Unieuro: nan
Euronics: smartphone galaxy s25 ultra 256gb
------------------------------
Expert: iphone 16 256gb
Unieuro: iphone 16 256gb
Euronics: iphone 16 256gb
------------------------------
Expert: 50 nxtpaper 8/256 5g
Unieuro: nan
Euronics: 50 nxtpaper
------------------------------
Expert: iphone 16 plus 256gb
Unieuro: iphone 16 256gb
Euronics: iphone 16 256gb
------------------------------
Expert: redmi 14c  8gb ram 256gb rom
Unieuro: nan
Euronics: smartphone redmi 14c 8+256gb
------------------------------
Expert: reno12 f 4g ai smartphone, camera 50+8+2mp, selfie 32mp, display 6,67 120hz amoled fhd+, 5000mah, 8+256gb,
Unieuro: reno12 f 4g ai smartphone, tripla fotocamera 50+8+2mp, selfie 32mp, display 6.67” 120hz amoled fhd+, 5000mah, ram 16 gb (8+8) + rom 256gb, [versione italia],
Euronics: nan
------------------------------
Expert: galaxy s25 ultra 12+256gb
Unieuro: nan
Euronics: smartphone galaxy s25 ultra 256gb
------------------------------
Expert: galaxy xcover7 5g  6+128gb
Unieuro: nan
Euronics: galaxy xcover7 5g
------------------------------
Expert: redmi a3  4gb ram 128gb rom
Unieuro: nan
Euronics: smartphone redmi a3 4+128gb
------------------------------
Expert: iphone 13 128gb
Unieuro: iphone 13 128gb
Euronics: iphone 13 128gb
------------------------------
Expert: galaxy a56 5g 8+256gb
Unieuro: nan
Euronics: smartphone galaxy a56 5g 256gb
------------------------------
Expert: 50 nxtpaper 8/256 5g grey
Unieuro: nan
Euronics: 50 nxtpaper-grey
------------------------------
Expert: iphone 16 pro 512gb
Unieuro: iphone 16 pro max 512gb
Euronics: iphone 16 pro max 512gb
------------------------------
Expert: redmi note 14 5g  8g ram 256g rom
Unieuro: nan
Euronics: redmi note 14 5g 8+256g
------------------------------
Expert: galaxy s25+ 12+512gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 512gb
------------------------------
Expert: iphone 16 128gb
Unieuro: iphone 16 128gb
Euronics: iphone 16 128gb
------------------------------
Expert: galaxy s25 ultra 12+1tb
Unieuro: nan
Euronics: smartphone galaxy s25 ultra 1tb
------------------------------
Expert: galaxy a36 5g 6+128gb
Unieuro: nan
Euronics: smartphone galaxy a36 5g 128gb
------------------------------
Expert: galaxy s25 12+256gb icy
Unieuro: nan
Euronics: smartphone galaxy s25 256gb-icy
------------------------------
Expert: iphone 16 plus 256gb
Unieuro: iphone 16 plus 256gb
Euronics: iphone 16 plus 256gb
------------------------------
Expert: galaxy a16 5g 4+128gb
Unieuro: nan
Euronics: smartphone galaxy a16 5g
------------------------------
Expert: galaxy s25+ 12+512gb
Unieuro: nan
Euronics: smartphone galaxy s25+ 512gb
------------------------------
Expert: galaxy s24 8+128gb
Unieuro: nan
Euronics: galaxy s24 256gb
------------------------------

In [10]:
quality_Unieuro = integrated[
    integrated['Unieuro Category'] == 'tv'
].dropna(subset=['Expert', 'Euronics'], thresh=1).sample(50)

quality_Unieuro.reset_index(drop=True, inplace=True)
quality_Unieuro

,Expert,Unieuro,Euronics,Expert Price,Unieuro Price,Euronics Price,Expert Category,Unieuro Category,Euronics Category,Expert Brand,Unieuro Brand,Euronics Brand,Expert Color,Unieuro Color,Euronics Color,Match Type
0,"oled65c55la tv oled evo ai serie c5 65'' 4k, 9...","oled evo ai oled65c55la tv serie c5 65'' 4k, α...",NaN,2699.0,2699.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
1,"tv ue50du7170uxzt crystal uhd 4k, smart tv 50""...","series 7 tv ue50cu7170uxzt crystal uhd 4k, sma...",NaN,377.9,332.00,NaN,tv,tv,NaN,samsung,samsung,NaN,lite black,lite black,NaN,2-way match
2,"oled55g54lw tv oled evo ai serie g5 55'' 4k, 1...","oled evo ai oled55g54lw tv serie g5 55'' 4k, α...",NaN,2299.0,2299.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
3,"smart tv 85"" qe85q7faauxzt qled 4k 2025","smart tv 85"" qe85q7faauxzt qled 4k 2025",NaN,1999.0,1999.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
4,"43nano82t6b tv nall ai serie nano82 43'' 4k, a...","nall ai 43'' serie nano82 43nano82t6b, tv 4k, ...",NaN,367.9,349.00,NaN,tv,tv,NaN,lg,lg,NaN,noce,noce,NaN,2-way match
5,ambilight tv the xtra 9008 65“ miniled 4k uhd ...,ambilight tv the xtra 9008 65“ miniled 4k uhd ...,NaN,885.9,799.00,NaN,tv,tv,NaN,philips,philips,NaN,unspecified,unspecified,NaN,2-way match
6,"smart tv 77"" qe77s90faexzt oled 4k 2025","smart tv 77"" qe77s90faexzt oled 4k 2025",NaN,3999.0,3999.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
7,"oled55b56la tv oled ai serie b5 55'' 4k, 8 gen...","oled ai oled55b56la tv serie b5 55'' 4k, α8 ge...",NaN,1499.0,1499.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
8,"oled48b46la tv oled ai serie b4 48'' 4k, a8, d...","oled b4 ai 48'' serie oled48b46la,tv 4k, 4 hdm...",NaN,786.9,675.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
9,"uhd 55'' serie ur78 55ur78006lk, tv 4k, 3 hdmi...","uhd 55'' serie ur78 55ur78006lk, tv 4k, 3 hdmi...",NaN,429.9,379.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
10,"smart tv 50"" qe50q7faauxzt qled 4k 2025","smart tv 50"" qe50q7faauxzt qled 4k 2025",NaN,649.0,649.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
11,"smart tv 77"" qe77s85faexzt oled 4k 2025","smart tv 77"" qe77s85faexzt oled 4k 2025",NaN,3299.0,3299.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
12,"smart tv 55"" qe55s85fauxzt oled 4k 2025","smart tv 55"" qe55s85fauxzt oled 4k 2025",NaN,1599.0,1599.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
13,"tv qled 144hz 100"" 4k ultra hd","tv qled 144hz 100"" 4k ultra hd 100e7nq pro",NaN,1599.0,1599.00,NaN,tv,tv,NaN,hisense,hisense,NaN,unspecified,unspecified,NaN,2-way match
14,"tv qe65q70datxzt qled 4k, smart tv 65"" process...","series 6 tv qe43q60cauxzt qled 4k, smart tv 43...",NaN,860.9,449.00,NaN,tv,tv,NaN,samsung,samsung,NaN,lite black,lite black,NaN,2-way match
15,"tv ue75du7170uxzt crystal uhd 4k, smart tv 75""...",tv crystal uhd 4k 75” ue75du7170uxzt smart tv ...,"smart tv led uhd 4k 75"" ue75du7170uxzt",657.9,630.00,648.0,tv,tv,tv,samsung,samsung,samsung,black,black,black,3-way match
16,"oled77b56la tv oled ai serie b5 77'' 4k, 8 gen...","oled ai oled77b56la tv serie b5 77'' 4k, α8 ge...",NaN,3299.0,3299.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
17,"uhd 65'' serie ur78 65ur78006lk, tv 4k, 3 hdmi...","uhd 65'' serie ur78 65ur78006lk, tv 4k, 3 hdmi...",NaN,544.0,519.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
18,"smart tv 65"" qe65s85faexzt oled 4k 2025","smart tv 65"" qe65s85faexzt oled 4k 2025",NaN,2299.0,2299.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
19,"50nano82t6b tv nall ai serie nano82 50'' 4k, a...","nall ai 50'' serie nano82 50nano82t6b, tv 4k, ...",NaN,480.9,423.00,NaN,tv,tv,NaN,lg,lg,NaN,noce,noce,NaN,2-way match
20,"oled65b42la tv oled ai serie b4 65'' 4k, a8, d...","oled b4 ai 65'' serie oled65b42la,tv 4k, 4 hdm...",NaN,1399.0,1199.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
21,"tv ue55cu8070uxzt crystal uhd 4k, smart tv 55""...","series 8 tv ue65cu8070uxzt crystal uhd 4k, sma...",NaN,699.0,599.00,NaN,tv,tv,NaN,samsung,samsung,NaN,black,black,NaN,2-way match
22,"oled55b46la tv oled ai serie b4 55'' 4k, a8, d...","oled b4 ai 55'' serie oled55b46la,tv 4k, 4 hdm...",NaN,882.9,799.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
23,ambilight tv 65pus8009 65“ 164cm 4k uhd led do...,"ambilight tv 65pus8510 4k uhd qled 164cm 65"" s...",NaN,632.9,799.00,NaN,tv,tv,NaN,philips,philips,NaN,unspecified,unspecified,NaN,2-way match
24,"oled83g54lw tv oled evo ai serie g5 83'' 4k, 1...","oled evo ai oled83g54lw tv serie g5 83'' 4k, α...",NaN,6499.0,6499.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
25,"ambilight tv 43pus9010 4k uhd qled 108cm 43"" s...","ambilight tv 43pus8510 4k uhd qled 108cm 43"" s...",NaN,699.0,449.00,NaN,tv,tv,NaN,philips,philips,NaN,unspecified,unspecified,NaN,2-way match
26,"oled65g54lw tv oled evo ai serie g5 65'' 4k, 1...","oled evo ai oled65g54lw tv serie g5 65'' 4k, α...",NaN,3299.0,3299.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
27,"ambilight tv 50pus8510 4k uhd qled 126cm 50"" s...","ambilight tv 50pus8510 4k uhd qled 126cm 50"" s...",NaN,599.0,549.00,NaN,tv,tv,NaN,philips,philips,NaN,unspecified,unspecified,NaN,2-way match
28,"uhd 43'' serie ur73 43ur73006la.apiq, tv 4k, 3...","uhd 50'' serie ur73 50ur73006la.apiq, tv 4k, 3...",NaN,349.9,329.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
29,"85"" led 4k uhd dolby vision hdr smart tv","tv led ultra hd 4k 85” 85a6dg smart tv, wifi, ...",NaN,799.0,799.90,NaN,tv,tv,NaN,hisense,hisense,NaN,unspecified,unspecified,NaN,2-way match
30,nall 75'' serie nano76 75nano766qa 4k smart tv...,nall 55'' serie nano76 55nano766qa 4k smart tv...,NaN,999.0,449.90,NaN,tv,tv,NaN,lg,lg,NaN,noce,noce,NaN,2-way match
31,"smart tv 85"" qe85q8faauxzt qled 4k 2025","smart tv 85"" qe85q8faauxzt qled 4k 2025",NaN,2199.0,2199.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
32,"tv qe43q60cauxzt qled 4k, smart tv 43"" process...","series 6 tv qe43q60cauxzt qled 4k, smart tv 43...",NaN,620.9,449.00,NaN,tv,tv,NaN,samsung,samsung,NaN,lite black,lite black,NaN,2-way match
33,"uhd 43'' serie ur78 43ur78006lk, tv 4k, 3 hdmi...","uhd 43'' serie ur78 43ur78006lk, tv 4k, 3 hdmi...",NaN,359.9,285.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
34,"75qned80t6a tv qned ai serie qned80 75'' 4k, a...","qned ai 75'' serie qned80 75qned80t6a, tv 4k, ...",NaN,1359.9,1799.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
35,"24tq510s monitor tv 24"" smart webos 22 wi-fi n...","24tq510s monitor tv 23.6"" smart webos 22 wi-fi...",NaN,205.9,143.99,NaN,pc desktop & monitor,tv,NaN,lg,lg,NaN,nero,nero,NaN,2-way match
36,hd ready 32'' serie lq630b 32lq630b6la smart tv,hd ready 32'' serie lq630b 32lq630b6la smart t...,NaN,204.9,188.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
37,"tv ue50du8070uxzt crystal uhd 4k, smart tv 50""...",tv crystal uhd 4k 50” ue50du8070uxzt smart tv ...,NaN,387.9,374.99,NaN,tv,tv,NaN,samsung,samsung,NaN,black,black,NaN,2-way match
38,smart tv 85” qe85qn90fatxzt neo qled 4k mini l...,smart tv 85” qe85qn90fatxzt neo qled 4k mini l...,NaN,4999.0,4999.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
39,"smart tv 75"" qe75q7faauxzt qled 4k 2025","smart tv 75"" qe75q7faauxzt qled 4k 2025",NaN,1499.0,1499.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
40,"oled55c44la tv oled evo ai serie c4 55'' 4k, a...",oled evo c4 oled55c48la tv ai serie c48 55'' 4...,NaN,1256.9,1199.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
41,"oled77c55la tv oled evo ai serie c5 77'' 4k, 9...","oled evo ai oled77c55la tv serie c5 77'' 4k, α...",NaN,3499.0,3499.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
42,"tv ue85du7170uxzt crystal uhd 4k, smart tv 85""...",tv crystal uhd 4k 85” ue85du7170uxzt smart tv ...,"smart tv led uhd 4k 85"" ue85du7170uxzt",878.9,899.00,780.0,tv,tv,tv,samsung,samsung,samsung,black,black,black,3-way match
43,"smart tv 48"" qe48s90faexzt oled 4k 2025","smart tv 48"" qe48s90faexzt oled 4k 2025",NaN,1499.0,1499.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
44,"smart tv 55"" qe55s95fatxzt oled 4k 2025","smart tv 55"" qe55s95fatxzt oled 4k 2025",NaN,2499.0,2499.00,NaN,tv,tv,NaN,samsung,samsung,NaN,unspecified,unspecified,NaN,2-way match
45,"oled77g54lw tv oled evo ai serie g5 77'' 4k, 1...","oled evo ai oled77g54lw tv serie g5 77'' 4k, α...",NaN,4299.0,4299.00,NaN,tv,tv,NaN,lg,lg,NaN,unspecified,unspecified,NaN,2-way match
46,"tv qe65s85daexzt oled 4k, smart tv 65"" process...",tv oled 4k 65” qe65s85daexzt smart tv wi-fi 2...,NaN,1227.9,1189.00,NaN,tv,tv,NaN,samsung,samsung,NaN,graphite black,graphite black,NaN,2-way match
47,"55nano82t6b tv nall ai serie nano82 55'' 4k, a...","nall ai 55'' serie nano82 55nano82t6b, tv 4k, ...",NaN,479.0,449.00,NaN,tv,tv,NaN,lg,lg,NaN,noce,noce,NaN,2-way match
48,"tv qe55s90daexzt oled 4k, smart tv 55"" process...",tv oled 4k 55” qe55s90daexzt smart tv wi-fi 2...,NaN,1078.9,999.00,NaN,tv,tv,NaN,samsung,samsung,NaN,graphite black,graphite black,NaN,2-way match
49,"tv qe55q70datxzt qled 4k, smart tv 55"" process...","series 6 tv qe43q60cauxzt qled 4k, smart tv 43...",NaN,707.9,449.00,NaN,tv,tv,NaN,samsung,samsung,NaN,lite black,lite black,NaN,2-way match

In [11]:
# Iterate over all rows in the quality_Unieuro dataframe
for i in range(len(quality_Unieuro)):
    # Print product matches in a more readable format
    print(f"Expert: {quality_Unieuro.iloc[i]['Expert']}")
    print(f"Unieuro: {quality_Unieuro.iloc[i]['Unieuro']}")
    print(f"Euronics: {quality_Unieuro.iloc[i]['Euronics']}")
    print('-' * 30)
    
#correct_matches = 41 over 50 = 82%

Expert: oled65c55la tv oled evo ai serie c5 65'' 4k, 9 gen8, brightness booster, 40w, 4 hdmi, vrr 144hz, smart tv webos 25
Unieuro: oled evo ai oled65c55la tv serie c5 65'' 4k, α9 gen8, brightness booster, 40w, 4 hdmi, vrr 144hz, smart tv webos 25
Euronics: nan
------------------------------
Expert: tv ue50du7170uxzt crystal uhd 4k, smart tv 50" processore crystal 4k, ots lite, black 2024
Unieuro: series 7 tv ue50cu7170uxzt crystal uhd 4k, smart tv 50" processore crystal 4k, ots lite, black 2023
Euronics: nan
------------------------------
Expert: oled55g54lw tv oled evo ai serie g5 55'' 4k, 11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Unieuro: oled evo ai oled55g54lw tv serie g5 55'' 4k, α11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Euronics: nan
------------------------------
Expert: smart tv 85" qe85q7faauxzt qled 4k 2025
Unieuro: smart tv 85" qe85q7faauxzt qled 4k 2025
Euronics: nan
------------------------------
Expert: 43nano82t6b tv nall ai serie nano82 43'' 4k, a5 gen7, hdr10, 20w, 3 hdmi, game optimizer, smart tv webos 24
Unieuro: nall ai 43'' serie nano82 43nano82t6b, tv 4k, 3 hdmi, smart tv 2024
Euronics: nan
------------------------------
Expert: ambilight tv the xtra 9008 65“ miniled 4k uhd dolby vision e dolby atmos
Unieuro: ambilight tv the xtra 9008 65“ miniled 4k uhd dolby vision e dolby atmos
Euronics: nan
------------------------------
Expert: smart tv 77" qe77s90faexzt oled 4k 2025
Unieuro: smart tv 77" qe77s90faexzt oled 4k 2025
Euronics: nan
------------------------------
Expert: oled55b56la tv oled ai serie b5 55'' 4k, 8 gen2, dolby vision, 20w, 4 hdmi con vrr 120hz, g-sync, smart tv webos 25
Unieuro: oled ai oled55b56la tv serie b5 55'' 4k, α8 gen2, dolby vision, 20w, 4 hdmi con vrr 120hz, g-sync, smart tv webos 25
Euronics: nan
------------------------------
Expert: oled48b46la tv oled ai serie b4 48'' 4k, a8, dolby vision, 20w, 4 hdmi con vrr, g-sync, smart tv webos 24
Unieuro: oled b4 ai 48'' serie oled48b46la,tv 4k, 4 hdmi, dolby vision, smart tv 2024
Euronics: nan
------------------------------
Expert: uhd 55'' serie ur78 55ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Unieuro: uhd 55'' serie ur78 55ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Euronics: nan
------------------------------
Expert: smart tv 50" qe50q7faauxzt qled 4k 2025
Unieuro: smart tv 50" qe50q7faauxzt qled 4k 2025
Euronics: nan
------------------------------
Expert: smart tv 77" qe77s85faexzt oled 4k 2025
Unieuro: smart tv 77" qe77s85faexzt oled 4k 2025
Euronics: nan
------------------------------
Expert: smart tv 55" qe55s85fauxzt oled 4k 2025
Unieuro: smart tv 55" qe55s85fauxzt oled 4k 2025
Euronics: nan
------------------------------
Expert: tv qled 144hz 100" 4k ultra hd
Unieuro: tv qled 144hz 100" 4k ultra hd 100e7nq pro
Euronics: nan
------------------------------
Expert: tv qe65q70datxzt qled 4k, smart tv 65" processore quantum 4k, ots lite, black 2024
Unieuro: series 6 tv qe43q60cauxzt qled 4k, smart tv 43" processore quantum 4k lite, ots lite, black 2023
Euronics: nan
------------------------------
Expert: tv ue75du7170uxzt crystal uhd 4k, smart tv 75"  2024
Unieuro: tv crystal uhd 4k 75” ue75du7170uxzt smart tv wi-fi  2024, processore crystal 4k, 4k upscaling, slim look design, ots lite
Euronics: smart tv led uhd 4k 75" ue75du7170uxzt
------------------------------
Expert: oled77b56la tv oled ai serie b5 77'' 4k, 8 gen2, dolby vision, 20w, 4 hdmi con vrr 120hz, g-sync, smart tv webos 25
Unieuro: oled ai oled77b56la tv serie b5 77'' 4k, α8 gen2, dolby vision, 20w, 4 hdmi con vrr 120hz, g-sync, smart tv webos 25
Euronics: nan
------------------------------
Expert: uhd 65'' serie ur78 65ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Unieuro: uhd 65'' serie ur78 65ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Euronics: nan
------------------------------
Expert: smart tv 65" qe65s85faexzt oled 4k 2025
Unieuro: smart tv 65" qe65s85faexzt oled 4k 2025
Euronics: nan
------------------------------
Expert: 50nano82t6b tv nall ai serie nano82 50'' 4k, a5 gen7, hdr10, 20w, 3 hdmi, game optimizer, smart tv webos 24
Unieuro: nall ai 50'' serie nano82 50nano82t6b, tv 4k, 3 hdmi, smart tv 2024
Euronics: nan
------------------------------
Expert: oled65b42la tv oled ai serie b4 65'' 4k, a8, dolby vision, 20w, 4 hdmi con vrr, g-sync, smart tv webos 24
Unieuro: oled b4 ai 65'' serie oled65b42la,tv 4k, 4 hdmi, dolby vision, smart tv 2024
Euronics: nan
------------------------------
Expert: tv ue55cu8070uxzt crystal uhd 4k, smart tv 55" processore crystal 4k, adaptive sound,  2023
Unieuro: series 8 tv ue65cu8070uxzt crystal uhd 4k, smart tv 65" processore crystal 4k, adaptive sound,  2023
Euronics: nan
------------------------------
Expert: oled55b46la tv oled ai serie b4 55'' 4k, a8, dolby vision, 20w, 4 hdmi con vrr, g-sync, smart tv webos 24
Unieuro: oled b4 ai 55'' serie oled55b46la,tv 4k, 4 hdmi, dolby vision, smart tv 2024
Euronics: nan
------------------------------
Expert: ambilight tv 65pus8009 65“ 164cm 4k uhd led dolby atmos titan os
Unieuro: ambilight tv 65pus8510 4k uhd qled 164cm 65" smart tv dolby atmos titan os
Euronics: nan
------------------------------
Expert: oled83g54lw tv oled evo ai serie g5 83'' 4k, 11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Unieuro: oled evo ai oled83g54lw tv serie g5 83'' 4k, α11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Euronics: nan
------------------------------
Expert: ambilight tv 43pus9010 4k uhd qled 108cm 43" smart tv dolby vision and dolby atmos titan os
Unieuro: ambilight tv 43pus8510 4k uhd qled 108cm 43" smart tv dolby atmos titan os
Euronics: nan
------------------------------
Expert: oled65g54lw tv oled evo ai serie g5 65'' 4k, 11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Unieuro: oled evo ai oled65g54lw tv serie g5 65'' 4k, α11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Euronics: nan
------------------------------
Expert: ambilight tv 50pus8510 4k uhd qled 126cm 50" smart tv dolby atmos titan os
Unieuro: ambilight tv 50pus8510 4k uhd qled 126cm 50" smart tv dolby atmos titan os
Euronics: nan
------------------------------
Expert: uhd 43'' serie ur73 43ur73006la.apiq, tv 4k, 3 hdmi, smart tv 2023
Unieuro: uhd 50'' serie ur73 50ur73006la.apiq, tv 4k, 3 hdmi, smart tv 2023
Euronics: nan
------------------------------
Expert: 85" led 4k uhd dolby vision hdr smart tv
Unieuro: tv led ultra hd 4k 85” 85a6dg smart tv, wifi, hdr dolby vision
Euronics: nan
------------------------------
Expert: nall 75'' serie nano76 75nano766qa 4k smart tv novità 2022
Unieuro: nall 55'' serie nano76 55nano766qa 4k smart tv novità 2022
Euronics: nan
------------------------------
Expert: smart tv 85" qe85q8faauxzt qled 4k 2025
Unieuro: smart tv 85" qe85q8faauxzt qled 4k 2025
Euronics: nan
------------------------------
Expert: tv qe43q60cauxzt qled 4k, smart tv 43" processore quantum 4k lite, ots lite, black 2023
Unieuro: series 6 tv qe43q60cauxzt qled 4k, smart tv 43" processore quantum 4k lite, ots lite, black 2023
Euronics: nan
------------------------------
Expert: uhd 43'' serie ur78 43ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Unieuro: uhd 43'' serie ur78 43ur78006lk, tv 4k, 3 hdmi, smart tv 2023
Euronics: nan
------------------------------
Expert: 75qned80t6a tv qned ai serie qned80 75'' 4k, a5 gen7, hdr10, 20w, 3 hdmi, game optimizer, smart tv webos 24
Unieuro: qned ai 75'' serie qned80 75qned80t6a, tv 4k, 3 hdmi, smart tv 2024
Euronics: nan
------------------------------
Expert: 24tq510s monitor tv 24" smart webos 22 wi-fi novità 2022
Unieuro: 24tq510s monitor tv 23.6" smart webos 22 wi-fi novità 2022
Euronics: nan
------------------------------
Expert: hd ready 32'' serie lq630b 32lq630b6la smart tv
Unieuro: hd ready 32'' serie lq630b 32lq630b6la smart tv novità 2022
Euronics: nan
------------------------------
Expert: tv ue50du8070uxzt crystal uhd 4k, smart tv 50" processore crystal 4k, adaptive sound,  2024
Unieuro: tv crystal uhd 4k 50” ue50du8070uxzt smart tv wi-fi  2024, processore crystal 4k, 4k upscaling, airslim design, ots lite
Euronics: nan
------------------------------
Expert: smart tv 85” qe85qn90fatxzt neo qled 4k mini led 2025
Unieuro: smart tv 85” qe85qn90fatxzt neo qled 4k mini led 2025
Euronics: nan
------------------------------
Expert: smart tv 75" qe75q7faauxzt qled 4k 2025
Unieuro: smart tv 75" qe75q7faauxzt qled 4k 2025
Euronics: nan
------------------------------
Expert: oled55c44la tv oled evo ai serie c4 55'' 4k, a9 gen7, brightness booster, 40w, 4 hdmi con vrr, g-sync, smart tv webos 24
Unieuro: oled evo c4 oled55c48la tv ai serie c48 55'' 4k, α9 gen7, brightness booster, 40w, 4 hdmi con vrr, g-sync, smart tv webos 24
Euronics: nan
------------------------------
Expert: oled77c55la tv oled evo ai serie c5 77'' 4k, 9 gen8, brightness booster, 40w, 4 hdmi, vrr 144hz, smart tv webos 25
Unieuro: oled evo ai oled77c55la tv serie c5 77'' 4k, α9 gen8, brightness booster, 40w, 4 hdmi, vrr 144hz, smart tv webos 25
Euronics: nan
------------------------------
Expert: tv ue85du7170uxzt crystal uhd 4k, smart tv 85"  2024
Unieuro: tv crystal uhd 4k 85” ue85du7170uxzt smart tv wi-fi  2024, processore crystal 4k, 4k upscaling, slim look design, ots lite
Euronics: smart tv led uhd 4k 85" ue85du7170uxzt
------------------------------
Expert: smart tv 48" qe48s90faexzt oled 4k 2025
Unieuro: smart tv 48" qe48s90faexzt oled 4k 2025
Euronics: nan
------------------------------
Expert: smart tv 55" qe55s95fatxzt oled 4k 2025
Unieuro: smart tv 55" qe55s95fatxzt oled 4k 2025
Euronics: nan
------------------------------
Expert: oled77g54lw tv oled evo ai serie g5 77'' 4k, 11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Unieuro: oled evo ai oled77g54lw tv serie g5 77'' 4k, α11 gen2, brightness booster ultimate, 60w, 4 hdmi 165hz, smart tv 2025
Euronics: nan
------------------------------
Expert: tv qe65s85daexzt oled 4k, smart tv 65" processore nq4 ai gen2, dolby atmos e ots lite,  2024
Unieuro: tv oled 4k 65” qe65s85daexzt smart tv wi-fi  2024, processore nq4 ai gen2, self-illuminating pixels, contour design, dolby atmos
Euronics: nan
------------------------------
Expert: 55nano82t6b tv nall ai serie nano82 55'' 4k, a5 gen7, hdr10, 20w, 3 hdmi, game optimizer, smart tv webos 24
Unieuro: nall ai 55'' serie nano82 55nano82t6b, tv 4k, 3 hdmi, smart tv 2024
Euronics: nan
------------------------------
Expert: tv qe55s90daexzt oled 4k, smart tv 55" processore nq4 ai gen2, dolby atmos e ots lite,  2024
Unieuro: tv oled 4k 55” qe55s90daexzt smart tv wi-fi  2024, processore nq4 ai gen2, self-illuminating pixels, laser slim design, dolby atmos
Euronics: nan
------------------------------
Expert: tv qe55q70datxzt qled 4k, smart tv 55" processore quantum 4k, ots lite, black 2024
Unieuro: series 6 tv qe43q60cauxzt qled 4k, smart tv 43" processore quantum 4k lite, ots lite, black 2023
Euronics: nan
------------------------------

In [12]:
quality_Euronics = integrated[
    integrated['Euronics Category'] == 'stampanti e scanner'
].dropna(subset=['Expert', 'Unieuro'], thresh=1).sample(50)

quality_Euronics.reset_index(drop=True, inplace=True)
quality_Euronics

,Expert,Unieuro,Euronics,Expert Price,Unieuro Price,Euronics Price,Expert Category,Unieuro Category,Euronics Category,Expert Brand,Unieuro Brand,Euronics Brand,Expert Color,Unieuro Color,Euronics Color,Match Type
0,912xl cartuccia di inchiostro originale alta c...,cartuccia di inchiostro originale 912xl ad al...,"912xl cartuccia di inchiostro originale, magenta",23.90,19.66,21.99,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,magenta,magenta,magenta,3-way match
1,304xl cartuccia di inchiostro originale alta c...,cartuccia inchiostro originale 304xl,ink 304xl-nero alta capacit?,38.90,37.90,37.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,nero,nero,nero,3-way match
2,"924 cartuccia d'inchiostro originale,",cartuccia di inchiostro originale 924,"924 cartuccia di inchiostro originale,giallo",13.90,13.90,14.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,giallo,giallo,giallo,3-way match
3,cli-551xl m,NaN,cli-551xl c-cyan,22.90,NaN,19.99,stampanti e multifunzione,NaN,stampanti e scanner,canon,NaN,canon,unspecified,NaN,unspecified,2-way match
4,304 combo pack cartucce originali e colore,NaN,"304 combo pack cartucce originali-nero, tricr...",33.90,NaN,39.90,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,nero,NaN,nero,2-way match
5,"62 cartuccia di inchiostro originale, tricromia",cartuccia originale inchiostro tricromia 62,305 cartuccia di inchiostro originale-tricromia,29.90,25.40,13.49,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,unspecified,unspecified,unspecified,3-way match
6,951xl cartuccia di inchiostro originale alta c...,cartuccia originale inchiostro ad alta capaci...,951xl cartuccia di inchiostro originale,50.90,42.90,39.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,ciano,ciano,magenta,3-way match
7,tn2410,NaN,tn2410 - toner serie l2000,59.99,NaN,54.90,stampanti e multifunzione,NaN,stampanti e scanner,brother,NaN,brother,unspecified,NaN,unspecified,2-way match
8,603 stella marina t03u standard single,NaN,603 stella marina t03u standard single nero,9.90,NaN,17.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,magenta,NaN,nero,2-way match
9,cl-511,cartuccia d'inchiostro colore cl-511 c/m/y,cl-511-colore,29.90,21.99,27.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,canon,canon,canon,unspecified,unspecified,unspecified,3-way match
10,"serie 604 ananas multipack nero std, ciano std...",NaN,cartuccia ink serie ananas multipack 604 std-n...,47.90,NaN,44.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,magenta,NaN,magenta,2-way match
11,"351 cartuccia di inchiostro originale, tricromia",NaN,351 cartuccia di inchiostro originale-tricromia,31.99,NaN,38.99,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,unspecified,NaN,unspecified,2-way match
12,c13t02e74020,NaN,"c13t02e74020-multipack (n,nf,c,m,g)",87.90,NaN,79.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,unspecified,NaN,unspecified,2-way match
13,workforce wf-2910dwf stampante multifunzione ...,NaN,multifunzione workforce wf-2910dwf,69.90,NaN,69.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,unspecified,NaN,unspecified,2-way match
14,cartuccia di inchiostro in tricromia originale...,NaN,308 cartuccia di inchiostro-tricromia,16.90,NaN,16.90,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,unspecified,NaN,unspecified,2-way match
15,cl-513 xl,NaN,cl-513 xl-colors,39.90,NaN,31.99,stampanti e multifunzione,NaN,stampanti e scanner,canon,NaN,canon,unspecified,NaN,unspecified,2-way match
16,"364 cartuccia di inchiostro originale,",cartuccia originale inchiostro 364,62 cartuccia di inchiostro originale,17.90,13.99,24.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,ciano,ciano,nero,3-way match
17,102 flacone di inchiostro ecotank t03r1,NaN,102 flacone di inchiostro ecotank t03r1 nero,15.49,NaN,15.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,nero,NaN,nero,2-way match
18,102 flacone di inchiostro ecotank t03r2,NaN,102 flacone di inchiostro ecotank t03r2 ciano,10.40,NaN,9.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,ciano,NaN,ciano,2-way match
19,cart.ink-jet 305,NaN,ink 305,13.99,NaN,14.90,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,nero,NaN,nero,2-way match
20,c13t16234012,NaN,c13t16234012-magente,10.99,NaN,11.99,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,unspecified,NaN,unspecified,2-way match
21,"963 cartuccia di inchiostro originale,",NaN,963,36.90,NaN,34.90,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,nero,NaN,nero,2-way match
22,inchiostro serie valigia 405 std,NaN,inchiostro serie valigia 405 std-nero std,25.90,NaN,25.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,nero,NaN,nero,2-way match
23,serie 604 ananas std t10g cartuccia di inchio...,NaN,cartuccia ink serie ananas nero 604 std,10.90,NaN,15.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,magenta,NaN,nero,2-way match
24,"924 cartuccia d'inchiostro originale,",cartuccia di inchiostro originale 924,"924 cartuccia di inchiostro originale,giallo",27.90,27.90,14.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,nero,nero,giallo,3-way match
25,inchiostro serie valigia 405xl,NaN,inchiostro serie valigia 405xl nero-nero xl,54.90,NaN,59.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,nero,NaN,nero,2-way match
26,su810a,NaN,su810a,72.90,NaN,79.90,stampanti e multifunzione,NaN,stampanti e scanner,samsung,NaN,samsung,unspecified,NaN,unspecified,2-way match
27,"44a cf244a cartuccia toner originale, compatib...",cartuccia toner originale laserjet 44a,toner nero 44a,69.90,56.99,69.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,nero,nero,nero,3-way match
28,301 tricromia,cartuccia originale inchiostro tricromia 301,301 cartuccia di inchiostro originale-tricromia,29.99,25.90,28.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,unspecified,unspecified,unspecified,3-way match
29,cli-571xl bk,NaN,cli-42 bk-bk,19.90,NaN,17.99,stampanti e multifunzione,NaN,stampanti e scanner,canon,NaN,canon,unspecified,NaN,unspecified,2-way match
30,expression home xp-3200 stampante multifunzion...,NaN,multifunzione expression xp-3200,74.90,NaN,69.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,unspecified,NaN,unspecified,2-way match
31,toner 207a,NaN,207a,102.40,NaN,74.99,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,giallo,NaN,nero,2-way match
32,toner 207a,NaN,207a,102.40,NaN,74.99,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,magenta,NaN,nero,2-way match
33,"22 cartuccia di inchiostro originale, colore",cartuccia originale inchiostro tricromia 22,cartuccia 22-tricromia,36.99,29.00,34.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,unspecified,unspecified,unspecified,3-way match
34,104 flacone di inchiostro ecotank t00p2,NaN,104 flacone di inchiostro ecotank t00p2 ciano,10.90,NaN,9.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,ciano,NaN,ciano,2-way match
35,premium glossy photo paper,photo paper glossy - a4 - 20 fogli,photo paper glossy 10x15cm 50 sheet,13.90,13.49,9.90,accessori informatica,stampanti e scanner,stampanti e scanner,epson,epson,epson,unspecified,unspecified,unspecified,3-way match
36,"304 cartuccia di inchiostro originale, tricromia",cartuccia inchiostro originale tricromia 304,305 cartuccia di inchiostro originale-tricromia,17.90,14.75,13.49,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,unspecified,unspecified,unspecified,3-way match
37,serie 604 ananas std t10g cartuccia di inchio...,NaN,cartuccia ink serie ananas nero 604 std,10.90,NaN,15.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,giallo,NaN,nero,2-way match
38,"21 cartuccia di inchiostro originale,",NaN,62 cartuccia di inchiostro originale,29.90,NaN,24.90,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,nero,NaN,nero,2-way match
39,cl-546 inchiostro colore,cartuccia d'inchiostro colore cl-546 c/m/y,cartuccia inchiostro colore cl-546-colore,29.90,24.99,26.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,canon,canon,canon,unspecified,unspecified,unspecified,3-way match
40,"924 cartuccia d'inchiostro originale,",cartuccia di inchiostro originale 924,"924 cartuccia di inchiostro originale,giallo",13.90,13.90,14.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,ciano,ciano,giallo,3-way match
41,102 flacone di inchiostro ecotank t03r3,NaN,102 flacone di inchiostro ecotank t03r3 magenta,10.40,NaN,9.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,magenta,NaN,magenta,2-way match
42,"302 cartuccia d'inchiostro originale, tricromia",cartuccia originale inchiostro tricromia 302,cartuccia colore 302-tricromia,27.90,27.99,25.99,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,unspecified,unspecified,unspecified,3-way match
43,"932/933 nero, ciano, giallo e , 6zc71ae, confe...",NaN,932/933 combo 4 cartucce originali nero e col...,80.90,NaN,73.99,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,magenta,NaN,magenta,2-way match
44,cl-41,NaN,cl-41-colors,34.90,NaN,31.90,stampanti e multifunzione,NaN,stampanti e scanner,canon,NaN,canon,unspecified,NaN,unspecified,2-way match
45,pixma mg3650s,NaN,pixma mg3650s,70.90,NaN,78.99,stampanti e multifunzione,NaN,stampanti e scanner,canon,NaN,canon,black,NaN,black,2-way match
46,305xl cartuccia di inchiostro originale alta c...,cartuccia di inchiostro originale ad alta cap...,"ink 305xl-nero, alta capacit?",26.90,22.90,29.90,stampanti e multifunzione,stampanti e scanner,stampanti e scanner,hp,hp,hp,nero,nero,nero,3-way match
47,toner 207a,NaN,207a,102.40,NaN,74.99,stampanti e multifunzione,NaN,stampanti e scanner,hp,NaN,hp,ciano,NaN,nero,2-way match
48,su100a,NaN,su100a,72.90,NaN,66.90,stampanti e multifunzione,NaN,stampanti e scanner,samsung,NaN,samsung,unspecified,NaN,unspecified,2-way match
49,c13t29814012,NaN,c13t29814012,16.99,NaN,16.90,stampanti e multifunzione,NaN,stampanti e scanner,epson,NaN,epson,unspecified,NaN,unspecified,2-way match

In [14]:
# Iterate over all rows in the quality_Unieuro dataframe
for i in range(len(quality_Euronics)):
    # Print product matches in a more readable format
    print(f"Expert: {quality_Euronics.iloc[i]['Expert']}")
    print(f"Unieuro: {quality_Euronics.iloc[i]['Unieuro']}")
    print(f"Euronics: {quality_Euronics.iloc[i]['Euronics']}")
    print('-' * 30)
    
#correct_matches = 43 over 50 = 86%

Expert: 912xl cartuccia di inchiostro originale alta capacità,
Unieuro: cartuccia di inchiostro  originale 912xl ad alta capacità
Euronics: 912xl cartuccia di inchiostro originale, magenta
------------------------------
Expert: 304xl cartuccia di inchiostro originale alta capacità ,
Unieuro: cartuccia inchiostro originale  304xl
Euronics: ink 304xl-nero alta capacit?
------------------------------
Expert: 924 cartuccia d'inchiostro originale,
Unieuro: cartuccia di inchiostro  originale 924
Euronics: 924 cartuccia di inchiostro originale,giallo
------------------------------
Expert: cli-551xl m
Unieuro: nan
Euronics: cli-551xl c-cyan
------------------------------
Expert: 304 combo pack cartucce originali  e colore
Unieuro: nan
Euronics: 304 combo pack cartucce originali-nero, tricromia
------------------------------
Expert: 62 cartuccia di inchiostro originale, tricromia
Unieuro: cartuccia originale inchiostro tricromia 62
Euronics: 305 cartuccia di inchiostro originale-tricromia
------------------------------
Expert: 951xl cartuccia di inchiostro originale alta capacità,
Unieuro: cartuccia originale inchiostro  ad alta capacità 951xl
Euronics: 951xl cartuccia di inchiostro originale
------------------------------
Expert: tn2410
Unieuro: nan
Euronics: tn2410 - toner serie l2000
------------------------------
Expert: 603 stella marina t03u standard single
Unieuro: nan
Euronics: 603 stella marina t03u standard single nero
------------------------------
Expert: cl-511
Unieuro: cartuccia d'inchiostro colore cl-511 c/m/y
Euronics: cl-511-colore
------------------------------
Expert: serie 604 ananas multipack nero std, ciano std,  std, giallo std, t10g cartuccia di inchiostro originale
Unieuro: nan
Euronics: cartuccia ink serie ananas multipack 604 std-nero/ciano/magenta/giallo
------------------------------
Expert: 351 cartuccia di inchiostro originale, tricromia
Unieuro: nan
Euronics: 351 cartuccia di inchiostro originale-tricromia
------------------------------
Expert: c13t02e74020
Unieuro: nan
Euronics: c13t02e74020-multipack (n,nf,c,m,g)
------------------------------
Expert: workforce wf-2910dwf  stampante multifunzione inkjet wireless display lcd usb stampa da mobile
Unieuro: nan
Euronics: multifunzione workforce wf-2910dwf
------------------------------
Expert: cartuccia di inchiostro in tricromia originale 308
Unieuro: nan
Euronics: 308 cartuccia di inchiostro-tricromia
------------------------------
Expert: cl-513 xl
Unieuro: nan
Euronics: cl-513 xl-colors
------------------------------
Expert: 364 cartuccia di inchiostro originale,
Unieuro: cartuccia originale inchiostro  364
Euronics: 62 cartuccia di inchiostro originale
------------------------------
Expert: 102  flacone di inchiostro ecotank t03r1
Unieuro: nan
Euronics: 102  flacone di inchiostro ecotank t03r1 nero
------------------------------
Expert: 102  flacone di inchiostro ecotank t03r2
Unieuro: nan
Euronics: 102  flacone di inchiostro ecotank t03r2 ciano
------------------------------
Expert: cart.ink-jet  305
Unieuro: nan
Euronics: ink 305
------------------------------
Expert: c13t16234012
Unieuro: nan
Euronics: c13t16234012-magente
------------------------------
Expert: 963 cartuccia di inchiostro originale,
Unieuro: nan
Euronics: 963
------------------------------
Expert: inchiostro  serie valigia 405 std
Unieuro: nan
Euronics: inchiostro  serie valigia 405 std-nero  std
------------------------------
Expert: serie 604 ananas  std t10g cartuccia di inchiostro originale
Unieuro: nan
Euronics: cartuccia ink serie ananas nero 604 std
------------------------------
Expert: 924 cartuccia d'inchiostro originale,
Unieuro: cartuccia di inchiostro  originale 924
Euronics: 924 cartuccia di inchiostro originale,giallo
------------------------------
Expert: inchiostro  serie valigia 405xl
Unieuro: nan
Euronics: inchiostro  serie valigia 405xl nero-nero xl
------------------------------
Expert: su810a
Unieuro: nan
Euronics: su810a
------------------------------
Expert: 44a cf244a cartuccia toner originale, compatibile con stampanti hp laserjet,
Unieuro: cartuccia toner  originale laserjet 44a
Euronics: toner nero 44a
------------------------------
Expert: 301 tricromia
Unieuro: cartuccia originale inchiostro tricromia 301
Euronics: 301 cartuccia di inchiostro originale-tricromia
------------------------------
Expert: cli-571xl bk
Unieuro: nan
Euronics: cli-42 bk-bk
------------------------------
Expert: expression home xp-3200 stampante multifunzione inkjet wireless display lcd usb stampa da mobile
Unieuro: nan
Euronics: multifunzione expression xp-3200
------------------------------
Expert: toner 207a
Unieuro: nan
Euronics: 207a
------------------------------
Expert: toner 207a
Unieuro: nan
Euronics: 207a
------------------------------
Expert: 22 cartuccia di inchiostro originale, colore
Unieuro: cartuccia originale inchiostro tricromia 22
Euronics: cartuccia 22-tricromia
------------------------------
Expert: 104  flacone di inchiostro ecotank t00p2
Unieuro: nan
Euronics: 104  flacone di inchiostro ecotank t00p2 ciano
------------------------------
Expert: premium glossy photo paper
Unieuro: photo paper glossy - a4 - 20 fogli
Euronics: photo paper glossy 10x15cm 50 sheet
------------------------------
Expert: 304 cartuccia di inchiostro originale, tricromia
Unieuro: cartuccia inchiostro originale tricromia 304
Euronics: 305 cartuccia di inchiostro originale-tricromia
------------------------------
Expert: serie 604 ananas  std t10g cartuccia di inchiostro originale
Unieuro: nan
Euronics: cartuccia ink serie ananas nero 604 std
------------------------------
Expert: 21 cartuccia di inchiostro originale,
Unieuro: nan
Euronics: 62 cartuccia di inchiostro originale
------------------------------
Expert: cl-546 inchiostro colore
Unieuro: cartuccia d'inchiostro colore cl-546 c/m/y
Euronics: cartuccia inchiostro colore cl-546-colore
------------------------------
Expert: 924 cartuccia d'inchiostro originale,
Unieuro: cartuccia di inchiostro  originale 924
Euronics: 924 cartuccia di inchiostro originale,giallo
------------------------------
Expert: 102  flacone di inchiostro ecotank t03r3
Unieuro: nan
Euronics: 102  flacone di inchiostro ecotank t03r3 magenta
------------------------------
Expert: 302 cartuccia d'inchiostro originale, tricromia
Unieuro: cartuccia originale inchiostro tricromia 302
Euronics: cartuccia colore 302-tricromia
------------------------------
Expert: 932/933 nero, ciano, giallo e , 6zc71ae, confezione da 4 cartucce originali hp
Unieuro: nan
Euronics: 932/933 combo 4 cartucce originali nero e colore-nero, ciano, magenta, giallo
------------------------------
Expert: cl-41
Unieuro: nan
Euronics: cl-41-colors
------------------------------
Expert: pixma mg3650s
Unieuro: nan
Euronics: pixma mg3650s
------------------------------
Expert: 305xl cartuccia di inchiostro originale alta capacità,
Unieuro: cartuccia di inchiostro  originale ad alta capacità 305xl
Euronics: ink 305xl-nero, alta capacit?
------------------------------
Expert: toner 207a
Unieuro: nan
Euronics: 207a
------------------------------
Expert: su100a
Unieuro: nan
Euronics: su100a
------------------------------
Expert: c13t29814012
Unieuro: nan
Euronics: c13t29814012
------------------------------

--> Accuracy ≈ 86%

### Redundancy

#### Expert:

In [19]:
# Step 1: Find all duplicates based on Expert + Price + Brand + Color
duplicate_rows = integrated.duplicated(subset=['Expert', 'Expert Price', 'Expert Brand', 'Expert Color'], keep=False)
duplicates_df = integrated[duplicate_rows].copy()

# Step 2: Group by Expert + Price + Brand + Color → count how many unique categories exist per group
category_counts = duplicates_df.groupby(
    ['Expert', 'Expert Price', 'Expert Brand', 'Expert Color']
)['Expert Category'].nunique().reset_index(name='Num_Categories')

# Step 3: Keep only groups where there is more than 1 unique category → these are the problematic ones
multi_category = category_counts[category_counts['Num_Categories'] > 1]

# Step 4: Reconstruct the final dataframe with only the duplicate rows having different categories
final_duplicates = duplicates_df.merge(
    multi_category[['Expert', 'Expert Price', 'Expert Brand', 'Expert Color']],
    on=['Expert', 'Expert Price', 'Expert Brand', 'Expert Color'],
    how='inner'
)

# Step 5: Print result
print(f"Found {final_duplicates.shape[0]} duplicated rows with DIFFERENT categories.")

# Display the most useful columns for manual review
final_duplicates[['Expert', 'Expert Price', 'Expert Brand', 'Expert Color', 'Expert Category', 'Unieuro Category', 'Euronics Category']].sort_values(by='Expert')

Found 62 duplicated rows with DIFFERENT categories.

,Expert,Expert Price,Expert Brand,Expert Color,Expert Category,Unieuro Category,Euronics Category
8,-link tapo tc65 - telecamera outdoor wi-fi/ether,44.90,tp,unspecified,networking,NaN,NaN
9,-link tapo tc65 - telecamera outdoor wi-fi/ether,44.90,tp,unspecified,smart home,NaN,NaN
0,-link tapo tc70 - telecamera pan/tilt wi-fi hd...,19.90,tp,unspecified,networking,NaN,NaN
1,-link tapo tc70 - telecamera pan/tilt wi-fi hd...,19.90,tp,unspecified,smart home,NaN,NaN
51,adattati o muori in una lotta contro la minacc...,69.99,activision,unspecified,xbox,NaN,NaN
...,...,...,...,...,...,...,...
7,ty1 telecamera motorizzata full hd,27.90,ezviz,unspecified,smart home,NaN,NaN
52,vivi un'epica avventura ricca di azione ambien...,79.90,ubisoft,unspecified,playstation,NaN,NaN
53,vivi un'epica avventura ricca di azione ambien...,79.90,ubisoft,unspecified,xbox,NaN,NaN
60,xbox headset e,59.99,microsoft,unspecified,xbox,NaN,NaN
61,xbox headset e,59.99,microsoft,unspecified,accessori informatica gaming,NaN,NaN

In [26]:
# Step 6: Remove problematic duplicates from the main dataframe

# Create a key to easily identify the groups to remove
multi_category['remove_key'] = multi_category['Expert'] + '||' + multi_category['Expert Price'].astype(str) + '||' + multi_category['Expert Brand'] + '||' + multi_category['Expert Color']

# Now create the same key in the original dataframe
integrated['remove_key'] = integrated['Expert'] + '||' + integrated['Expert Price'].astype(str) + '||' + integrated['Expert Brand'] + '||' + integrated['Expert Color']

# Filter out the problematic rows
integrated_no_duplicates = integrated[~integrated['remove_key'].isin(multi_category['remove_key'])].copy()

# Drop the temporary column
integrated_no_duplicates.drop(columns=['remove_key'], inplace=True)

# Print result
print(f"Original dataframe had {integrated.shape[0]} rows.")
print(f"Cleaned dataframe has {integrated_no_duplicates.shape[0]} rows. {integrated.shape[0] - integrated_no_duplicates.shape[0]} rows were removed.")
integrated_no_duplicates

Original dataframe had 10546 rows.
Cleaned dataframe has 10484 rows. 62 rows were removed.

<ipython-input-26-9f4616a30e25>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  multi_category['remove_key'] = multi_category['Expert'] + '||' + multi_category['Expert Price'].astype(str) + '||' + multi_category['Expert Brand'] + '||' + multi_category['Expert Color']

,Expert,Unieuro,Euronics,Expert Price,Unieuro Price,Euronics Price,Expert Category,Unieuro Category,Euronics Category,Expert Brand,Unieuro Brand,Euronics Brand,Expert Color,Unieuro Color,Euronics Color,Match Type
0,iphone 16 128gb,iphone 16 128gb,iphone 16 128gb,888.90,779.0,979.0,smartphone & cellulari,smartphone e cellulari,smartphone e cellulari,apple,apple,apple,nero,nero,nero,3-way match
1,galaxy s24 8+256gb onyx,NaN,galaxy s24 256gb-onyx,707.90,NaN,599.0,smartphone & cellulari,NaN,smartphone e cellulari,samsung,NaN,samsung,black,NaN,black,2-way match
2,galaxy s25 ultra 12+512gb,NaN,NaN,1614.90,NaN,NaN,smartphone & cellulari,NaN,NaN,samsung,NaN,NaN,titanium silverblue,NaN,NaN,1-way only
3,redmi note 14 5g 8g ram 256g rom,NaN,redmi note 14 5g 8+256g,255.90,NaN,299.9,smartphone & cellulari,NaN,smartphone e cellulari,xiaomi,NaN,xiaomi,midnight black,NaN,midnight black,2-way match
4,"edge 50 neo, 8/256gb, fotocamera sony lytia™ 7...",NaN,NaN,341.90,NaN,NaN,smartphone & cellulari,NaN,NaN,motorola,NaN,NaN,unspecified,NaN,NaN,1-way only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10541,6206301401,NaN,NaN,11.99,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10542,6016101401,NaN,NaN,4.50,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10543,6430101401,NaN,NaN,2.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10544,pila bottone x eletronica cr2450 litio,NaN,NaN,3.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only
10545,4276101401,NaN,NaN,1.49,NaN,NaN,bricolage & materiale elettrico,NaN,NaN,varta,NaN,NaN,unspecified,NaN,NaN,1-way only

In [27]:
integrated_no_duplicates.to_csv("Integrated_No_Duplicates.csv", index=False)

#### Unieuro:

In [21]:
# Step 1: Find all duplicates based on Unieuro + Price + Brand + Color
duplicate_rows_unieuro = integrated.duplicated(subset=['Unieuro', 'Unieuro Price', 'Unieuro Brand', 'Unieuro Color'], keep=False)
duplicates_df_unieuro = integrated[duplicate_rows_unieuro].copy()

# Step 2: Group by Unieuro + Price + Brand + Color → count how many unique categories exist per group
category_counts_unieuro = duplicates_df_unieuro.groupby(
    ['Unieuro', 'Unieuro Price', 'Unieuro Brand', 'Unieuro Color']
)['Unieuro Category'].nunique().reset_index(name='Num_Categories')

# Step 3: Keep only groups where there is more than 1 unique category → these are the problematic ones
multi_category_unieuro = category_counts_unieuro[category_counts_unieuro['Num_Categories'] > 1]

# Step 4: Reconstruct the final dataframe with only the duplicate rows having different categories
final_duplicates_unieuro = duplicates_df_unieuro.merge(
    multi_category_unieuro[['Unieuro', 'Unieuro Price', 'Unieuro Brand', 'Unieuro Color']],
    on=['Unieuro', 'Unieuro Price', 'Unieuro Brand', 'Unieuro Color'],
    how='inner'
)

# Step 5: Print result
print(f"Found {final_duplicates_unieuro.shape[0]} duplicated rows for Unieuro with DIFFERENT categories.")

# Display the most useful columns for manual review
final_duplicates_unieuro[['Unieuro', 'Unieuro Price', 'Unieuro Brand', 'Unieuro Color', 'Unieuro Category', 'Expert Category', 'Euronics Category']].sort_values(by='Unieuro')

Found 0 duplicated rows for Unieuro with DIFFERENT categories.

Empty DataFrame
Columns: [Unieuro, Unieuro Price, Unieuro Brand, Unieuro Color, Unieuro Category, Expert Category, Euronics Category]
Index: []

#### Euronics:

In [23]:
# Step 1: Find all duplicates based on Euronics + Price + Brand + Color
duplicate_rows_euronics = integrated.duplicated(subset=['Euronics', 'Euronics Price', 'Euronics Brand', 'Euronics Color'], keep=False)
duplicates_df_euronics = integrated[duplicate_rows_euronics].copy()

# Step 2: Group by Euronics + Price + Brand + Color → count how many unique categories exist per group
category_counts_euronics = duplicates_df_euronics.groupby(
    ['Euronics', 'Euronics Price', 'Euronics Brand', 'Euronics Color']
)['Euronics Category'].nunique().reset_index(name='Num_Categories')

# Step 3: Keep only groups where there is more than 1 unique category → these are the problematic ones
multi_category_euronics = category_counts_euronics[category_counts_euronics['Num_Categories'] > 1]

# Step 4: Reconstruct the final dataframe with only the duplicate rows having different categories
final_duplicates_euronics = duplicates_df_euronics.merge(
    multi_category_euronics[['Euronics', 'Euronics Price', 'Euronics Brand', 'Euronics Color']],
    on=['Euronics', 'Euronics Price', 'Euronics Brand', 'Euronics Color'],
    how='inner'
)

# Step 5: Print result
print(f"Found {final_duplicates_euronics.shape[0]} duplicated rows for Euronics with DIFFERENT categories.")

# Display the most useful columns for manual review
final_duplicates_euronics[['Euronics', 'Euronics Price', 'Euronics Brand', 'Euronics Color', 'Euronics Category', 'Expert Category', 'Unieuro Category']].sort_values(by='Euronics')

Found 0 duplicated rows for Euronics with DIFFERENT categories.

Empty DataFrame
Columns: [Euronics, Euronics Price, Euronics Brand, Euronics Color, Euronics Category, Expert Category, Unieuro Category]
Index: []